@Library('jenkins-upstream-library') _

pipeline {
	agent {
        kubernetes {
            inheritFrom 'jenkins-agent'
        }
    }
    environment {
        IBMCLOUD_API_KEY = credentials('IBMCLOUD_UPSTREAM_CI_API_KEY')
        CRN = "crn:v1:bluemix:public:cloud-object-storage:global:a/7cfbd5381a434af7a09289e795840d4e:28b5b206-4182-4324-8f5d-0d9234989a92::"
        CLUSTER_ID = "ccvt6cad05vojajdanig"
        JENKINS_BUCKET = "ibm-internal-cicd-jenkins-backup-bucket"
        INFLUXDB_BUCKET = "ibm-internal-cicd-infuxdb-backup-bucket"
    }

    stages {
        stage('Create Backup') {
            steps {
		        script {
		            sh '''#!/bin/bash
                        chmod +x ./scripts/prepare-backup.sh
                        ./scripts/prepare-backup.sh 2>&1 | tee backup.log
		            '''
		        }
            }
        }
    }
    post {
        always {
            archiveAllArtifacts("backup.log")
            cleanWs()
        }
    }
}
