@Library('jenkins-upstream-library') _
//Define Global variable
def INSTANCE_NAME_LIST = [
                    "rdr-ocp-cicd-montreal01",
                    "rdr-ocp-cicd-osaka21",
                    "rdr-ocp-cicd-sydney05",
                    "rdr-ocp-cicd-tokyo04",
                    "rdr-ocp-cicd-toronto01",
                    "rdr-ocp-cicd-london06",
                    "rdr-ocp-upi-validation-osa21",
                    "rdr-ocp-upi-validation-tor01",
                    "rdr-ocp-storage-sao01-odf",
                    "rdr-ocp-storage-lon06-odf",
                    "rdr-ocp-storage-syd05-odf",
                    "rdr-ocp-storage-osa21-odf"
                    ]
pipeline {
    agent {
        kubernetes {
            inheritFrom 'jenkins-agent'
        }
    }
    options {
        copyArtifactPermission('*');
    }
    environment {
        //users and credentials. All must be defined in Jenkins Credentials
        IBM_CLOUD_API_KEY = credentials('IBMCLOUD_UPSTREAM_CI_API_KEY')
        PCLOUD_IBM_API_KEY = credentials('IBM_PCLOUD_QE_API_KEY')
        ODF_IBMCLOUD_API_KEY = credentials('ODF_IBMCLOUD_API_KEY')
        PVSADM_VERSION = "v0.1.7"
    }
    stages {
        stage('Pull PowerVS Images') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    sh(returnStatus: false, returnStdout: false, script: "curl -sL https://raw.githubusercontent.com/ppc64le-cloud/pvsadm/master/get.sh | VERSION=${PVSADM_VERSION} FORCE=1 bash; pvsadm version")
                    INSTANCE_NAME_LIST.each { item ->
                        if(item.matches("rdr-ocp-upi-validation-(.*)")){
                            env.IBMCLOUD_API_KEY = env.PCLOUD_IBM_API_KEY
                        }
                        else if(item.matches("(.*)odf(.*)")){
                            env.IBMCLOUD_API_KEY = env.ODF_IBMCLOUD_API_KEY
                        }
                        else {
                            env.IBMCLOUD_API_KEY = env.IBM_CLOUD_API_KEY
                        }
                        sh """
                            pvsadm purge images --dry-run --instance-name '${item}' |grep 'tier1' |grep 'active' > images_all_'${item}'.txt
                            cat images_all_'${item}'.txt | grep 'rhel-83'  |sort -t'|' -k5 -r|head -1|grep -o 'rhel-83-[[:alnum:]]*-tier1'|xargs > latest-rhel-83-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhel-84'  |sort -t'|' -k5 -r|head -1|grep -o 'rhel-84-[[:alnum:]]*-tier1'|xargs > latest-rhel-84-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhel-85'  |sort -t'|' -k5 -r|head -1|grep -o 'rhel-85-[[:alnum:]]*-tier1'|xargs > latest-rhel-85-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhel-86'  |sort -t'|' -k5 -r|head -1|grep -o 'rhel-86-[[:alnum:]]*-tier1'|xargs > latest-rhel-86-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhel-9'  |sort -t'|' -k5 -r|head -1|grep -o 'rhel-9-[[:alnum:]]*-tier1'|xargs > latest-rhel-9-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhcos-46' |sort -t'|' -k5 -r|head -1|grep -o 'rhcos-46-[[:alnum:]]*-tier1'|xargs > latest-rhcos-46-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhcos-47' |sort -t'|' -k5 -r|head -1|grep -o 'rhcos-47-[[:alnum:]]*-tier1'|xargs > latest-rhcos-47-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhcos-48' |sort -t'|' -k5 -r|head -1|grep -o 'rhcos-48-[[:alnum:]]*-tier1'|xargs > latest-rhcos-48-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhcos-49' |sort -t'|' -k5 -r|head -1|grep -o 'rhcos-49-[[:alnum:]]*-tier1'|xargs > latest-rhcos-49-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhcos-410' |sort -t'|' -k5 -r|head -1|grep -o 'rhcos-410-[[:alnum:]]*-tier1'|xargs > latest-rhcos-410-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhcos-411' |sort -t'|' -k5 -r|head -1|grep -o 'rhcos-411-[[:alnum:]]*-tier1'|xargs > latest-rhcos-411-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhcos-412' |sort -t'|' -k5 -r|head -1|grep -o 'rhcos-412-[[:alnum:]]*-tier1'|xargs > latest-rhcos-412-'${item}'.txt || true
                            cat images_all_'${item}'.txt | grep 'rhcos-413' |sort -t'|' -k5 -r|head -1|grep -o 'rhcos-413-[[:alnum:]]*-tier1'|xargs > latest-rhcos-413-'${item}'.txt || true
                        """
                    }
                }
            }
        }
    }
    post {
        always {
            script{
                INSTANCE_NAME_LIST.each { item ->
                    archiveArtifacts allowEmptyArchive: true, artifacts: "images_all_${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhel-83-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhel-84-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhel-85-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhel-86-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhel-9-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhcos-46-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhcos-47-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhcos-48-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhcos-49-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhcos-410-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhcos-411-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhcos-412-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                    archiveArtifacts allowEmptyArchive: true, artifacts: "latest-rhcos-413-${item}.txt", fingerprint: true, onlyIfSuccessful: false
                }
            }
            cleanWs()
        }
    }
}
