@Library('jenkins-upstream-library') _

pipeline {
    agent {
        docker {
            image 'quay.io/powercloud/inbound-agent:4.10-3.3'
            args '-v /etc/resolv.conf:/etc/resolv.conf.tmp '
            label 'jump-vpc-x86_64'
        }
    }
    parameters {
        string(defaultValue: '', description: 'OCP version on which OCS/ODF will be deployed', name: 'ocpVersion')
        string(defaultValue: '', description: 'OCS version which you want to upgrade', name: 'ocsVersion')
        string(defaultValue: '', description: 'rhceph-dev/ocs-registry Image used for deploying OCS/ODF', name: 'ocsRegistryImage')
        string(defaultValue: '', description: 'OCS version in which you want to upgrade', name: 'ocsUpgradeVersion')
        string(defaultValue: '', description: 'rhceph-dev/ocs-registry image of upgraded ocs version', name: 'ocsUpgradeRegistryImage')
        booleanParam(defaultValue: false, description: 'Enable/Disable Vault', name: 'Vault')
        booleanParam(defaultValue: false, description: 'Enable/Disable Fips', name: 'Fips')
        choice(choices: ['1', '2', '3', '4a', '4b','4c' ],name: 'TierTest')
        string(defaultValue: '720', description: 'Enter time(in Minutes) to retain the cluster', name: 'KeepFor')
    }
     environment {
        //users and credentials. All must be defined in Jenkins Credentials
        GITHUB_USER = credentials('GITHUB_USER')
        OS_USERNAME = credentials('OS_USERNAME')
        OS_PASSWORD = credentials('OS_PASSWORD')
        DOCKER_USER = credentials('DOCKER_USER')
        ARTIFACTORY_USER = credentials('ARTIFACTORY_USER')
        ARTIFACTORY_TOKEN = credentials('ARTIFACTORY_TOKEN')
        GITHUB_TOKEN = credentials('GITHUB_TOKEN')
        REDHAT_USERNAME = credentials('REDHAT_USERNAME')
        REDHAT_PASSWORD = credentials('REDHAT_PASSWORD')
        PULL_SECRET = credentials('ODF_PULL_SECRET')
        OS_AUTH_URL=credentials('URL_SCNLCICDPOWERVC')


        // Parameters
        OCP_RELEASE = "${params.ocpVersion}"
        ODF_VERSION = "${params.ocsVersion}"
        UPGRADE_OCS_VERSION = "${params.ocsUpgradeVersion}"
        OCS_REGISTRY_IMAGE = "${params.ocsRegistryImage}"
        UPGRADE_OCS_REGISTRY = "${params.ocsUpgradeRegistryImage}"
        ENABLE_VAULT = "${params.Vault}"
        ENABLE_FIPS = "${params.Fips}"
        TIER_TEST = "${params.TierTest}"
        TIMEOUT = "${params.KeepFor}"

        //Env constants
        HARDWARE_CHOSE = "P9"
        TERRAFORM_VER = "1.2.0"
        AVAILABILITY_ZONE = "p9"
        POWERVS = false
        SCRIPT_DEPLOYMENT = false
        WAIT_FOR_DEBUG = "1"

        //Branch
        OPENSHIFT_POWERVC_GIT_TF_DEPLOY_BRANCH="main"//The download branch

        TARGET = "deploy-openshift4-powervc"
        TEMPLATE_FILE = ".${TARGET}.tfvars.template"

        // ODF Variables
        PLATFORM = "powervm"
       // OCS_REGISTRY_IMAGE="quay.io/rhceph-dev/ocs-registry:latest-stable-4.11.0"
        CONFIG_TYPE = "odf"

	 }
    stages {
        stage('Setup Common Environment Variables') {
            steps {
                setupCommonEnvironmentVariables()
                setupClusterConfig("${CONFIG_TYPE}")
            }
        }
        stage('Setting RHEL Image as per OCP version') {
            steps {
                script {
                    switch (env.OCP_RELEASE) {
                        case "4.6":
                            env.REDHAT_RELEASE = "8.3"
                            break
                        case "4.7":
                            env.REDHAT_RELEASE = "8.3"
                            break
                        case "4.8":
                            env.REDHAT_RELEASE = "8.3"
                            break
                        case "4.9":
                            env.REDHAT_RELEASE = "8.4"
                            break
                        case "4.10":
                            env.REDHAT_RELEASE = "8.4"
                            break
                        case "4.11":
                            env.REDHAT_RELEASE = "8.5"
                            break
                        case "4.12":
                            env.REDHAT_RELEASE = "8.6"
                            break
                        case "4.13":
                            env.REDHAT_RELEASE = "9.0"
                            break
                        default:
                            env.REDHAT_RELEASE = "9.2"
                    }
                }
            }
        }

        stage('pull artifact') {
            steps {
                getArtifacts("mirror-openshift-release", "latest-${OCP_RELEASE}-build.txt" )
                getArtifacts("powervm/poll-powervc-images", "cicd-rhcos-${OCP_RELEASE}.latest.txt")
                getArtifacts("powervm/poll-powervc-images", "cicd-rhel-${REDHAT_RELEASE}.latest.txt")
            }
        }
        //Checkout the installer git repo
        stage('Prepare Terraform Template') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {
                        pullSecret()
                        gbToMb()
                        env.OPENSHIFT_IMAGE = ""
                        env.OCP_RELEASE_TAG = ""
                        if (fileExists("deploy/artifactory/latest-${OCP_RELEASE}-build.txt")) {
                            env.OPENSHIFT_IMAGE = readFile "deploy/artifactory/latest-${OCP_RELEASE}-build.txt"
                            env.OPENSHIFT_IMAGE = env.OPENSHIFT_IMAGE.trim()
                            env.OCP_RELEASE_TAG = env.OPENSHIFT_IMAGE.split(":")[1].trim()
                        }
                        else {
                            echo "latest-${OCP_RELEASE}-build.txt file does not exist. Please check mirror-openshift-release job"
                            throw err
                        }
                        if (fileExists("deploy/artifactory/cicd-rhcos-${OCP_RELEASE}.latest.txt")) {
                            env.RHCOS_IMAGE = readFile "deploy/artifactory/cicd-rhcos-${OCP_RELEASE}.latest.txt"
                            env.RHCOS_IMAGE_NAME = env.RHCOS_IMAGE.split()[0].trim()
                            env.RHCOS_IMAGE_ID = env.RHCOS_IMAGE.split()[1].trim()
                        }
                        else {
                            echo "cicd-rhel-${REDHAT_RELEASE}.latest.txt file does not exist. Please check poll-powervc-images job"
                            throw err
                        }
                        if (fileExists("deploy/artifactory/cicd-rhel-${REDHAT_RELEASE}.latest.txt")) {
                            env.BASTION_IMAGE = readFile "deploy/artifactory/cicd-rhel-${REDHAT_RELEASE}.latest.txt"
                            env.BASTION_IMAGE_NAME = env.BASTION_IMAGE.split()[0].trim()
                            env.BASTION_IMAGE_ID = env.BASTION_IMAGE.split()[1].trim()
                        }
                        else {
                            echo "cicd-rhel-${REDHAT_RELEASE}.latest.txt file does not exist. Please check poll-powervc-images job"
                            throw err
                        }
                        createTemplate(env.OS_AUTH_URL, env.MASTER_VCPUS , "${MASTER_MEMORY_MB}", env.MASTER_PROCESSORS, env.MASTER_TEMPLATE)
                        createTemplate(env.OS_AUTH_URL, env.WORKER_VCPUS , "${WORKER_MEMORY_MB}", env.WORKER_PROCESSORS, env.WORKER_TEMPLATE)
                        createTemplate(env.OS_AUTH_URL, env.BASTION_VCPUS , "${BASTION_MEMORY_MB}", env.BASTION_PROCESSORS, env.BASTION_TEMPLATE)
                        createTemplate(env.OS_AUTH_URL, env.BOOTSTRAP_VCPUS , "${BOOTSTRAP_MEMORY_MB}", env.BOOTSTRAP_PROCESSORS, env.BOOTSTRAP_TEMPLATE)
                    }
                    catch (err)
                    {
                        echo 'Error ! Template preparation failed !'
                        env.FAILED_STAGE=env.STAGE_NAME
                        throw err
                    }
                }
            }
        }
        stage('Initialize Environment') {
            steps {
                initializeEnvironment()
                script {
                    env.OS_PRIVATE_NETWORK="icp_network2"
                    env.OS_NETWORK="icp_network2"
                    //env.SCG_ID = "8a5ff38d-0e88-40bd-8bc3-2d1434789461"
                    //env.NETWORK_TYPE = "SRIOV"
                    env.CNI_NETWORK_PROVIDER = "OpenshiftSDN"
                }
            }
        }
        stage('Setup Terraform Plugin') {
            steps {
                setupTerraformPlugin()
            }
        }
        stage('Deploy OCP Cluster') {
            steps {
                deployCluster()
            }
        }
        stage('Setup Kubectl') {
            steps {
                setupKubeconfigOcp4()
            }
        }
        stage('Run ODF Setup script') {
            steps {
                odfAuthYaml()
                odfRunSetupScript()
            }
        }
        stage('Run ODF deploy script') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try {
                        sh '''
                            cd ${WORKSPACE}/scripts/odf
                            chmod +x run-odf-deploy.sh
                            ./run-odf-deploy.sh
                        '''
                    }
                    catch (err) {
                        echo 'Error ! ODF deploy script failed!'
                        env.FAILED_STAGE=env.STAGE_NAME
                        throw err
                    }
                }
            }
        }
        stage('Capture output of multiple commands to verify before ODF upgrade') {
            steps {
                odfRunCommands()
            }
        }
        stage('Upgrading ODF') {
            steps {
                script {
                        ansiColor('xterm') {
                            echo ""
                        }
                        try {
                            sh '''
                               cd ${WORKSPACE}/scripts/odf
                               chmod +x run-odf-upgrade.sh
                               ./run-odf-upgrade.sh
                               '''
                            env.ODF_FULL_BUILD = readFile "${WORKSPACE}/odf-full-build.txt"

                        }
                        catch (err) {
                            echo 'Error ! ODF Upgrade using upgrade-ocs-ci.sh failed!'
                            env.FAILED_STAGE=env.STAGE_NAME
                            throw err
                        }
                }
            }
        }
        stage('Capture output of multiple commands to verify after ODF upgrade') {
            steps {
                odfRunCommands()
            }
        }
        stage('Run ODF tier tests') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try {
                        sh '''
                            cd ${WORKSPACE}/scripts/odf
                            chmod +x run-tier-tests.sh
                            chmod +x fix-config.sh
                            ./fix-config.sh
                            ./run-tier-tests.sh
                        '''
                    }
                    catch (err) {
                        echo 'Error ! Tier test script failed!'
                        env.FAILED_STAGE=env.STAGE_NAME
                        throw err
                    }
                 }
             }
        }
        stage('Waiting to timeout') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try {
                            TIMEOUT_MIN = TIMEOUT.toInteger()
                            if ( TIMEOUT_MIN != 0 )
                            {
                                TIMEOUT_SEC=TIMEOUT_MIN*60
                                echo "HOLDING THE CLUSTER TEAR DOWN FOR ${TIMEOUT_MIN} MINUTES"
                                sleep TIMEOUT_SEC
                            }
                        }
                    catch (err) {
                            echo 'Error ! Timeout stage failed!'
                            env.FAILED_STAGE=env.STAGE_NAME
                            throw err
                    }
                }
            }
        }
    }
    post {
        always {
            archiveAllArtifacts("results.tar.gz", "tier${TIER_TEST}-summary.txt", "odf-commands.txt")
            cleanupOcp4Cluster()
            checkInfraError()
            odfProcessTierTestResults()
            //notifyBySlack(currentBuild.result, env.MESSAGE)
            cleanWs()
        }
    }
}


