@Library('jenkins-upstream-library') _
pipeline {
    agent {
        kubernetes {
            inheritFrom 'jenkins-agent'
        }
    }
    options {
        copyArtifactPermission('*');
    }
    environment {
        //users and credentials. All must be defined in Jenkins Credentials
        ARTIFACTORY_USER = credentials('ARTIFACTORY_USER')
        ARTIFACTORY_TOKEN = credentials('ARTIFACTORY_TOKEN')
        CI_OCP_TOKEN_2 = credentials('CI_OCP_TOKEN_2')
    }
    stages {
        stage('Get images and push') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {
                    sh '''
                        cd ${WORKSPACE}/scripts
                        nerdctl login -u ${ARTIFACTORY_USER} -p ${ARTIFACTORY_TOKEN} sys-powercloud-docker-local.artifactory.swg-devops.com
                        wget https://mirror.openshift.com/pub/openshift-v4/clients/oc/4.3/linux/oc.tar.gz -O /tmp/oc.tar.gz
                        tar zvxf /tmp/oc.tar.gz
                        chmod +x oc
                        export PATH=$PATH:$PWD
                        oc login --token=${CI_OCP_TOKEN_2} --server=https://api.ci.l2s4.p1.openshiftapps.com:6443
                        oc registry login --skip-check
                        ./mirror-images.sh || true
                    '''
                    }
                    catch (err)
                    {
                        echo 'Error ! Mirroring Failed!'
                        throw err
                    }
                }
            }
        }

        stage('Prepare Terraform Template') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {
                    sh '''
                    curl https://openshift-release-ppc64le.apps.ci.l2s4.p1.openshiftapps.com/ > builds.raw.txt
                    cat builds.raw.txt | grep -A 2 '<td class="text-monospace"' | grep -v '^--' | awk 'NR%3{printf "%s ",$0;next;}1'|grep -v 'Failed' |sed 's|\\([^/]*/\\)\\{4\\}[^>]*>\\([^>]*\\).*title[^"]*"\\([^"]*\\).*|\\2  \\3|' | sed 's/<\\/a//'| sort -k2 -r |awk '{print "sys-powercloud-docker-local.artifactory.swg-devops.com/ocp-ppc64le/release-ppc64le:"$0}' > all-builds.txt
                    #All Builds
                    grep '4\\.6\\.[0-9]\\?[0-9]' all-builds.txt > all-4.6-builds.txt
                    grep '4\\.7\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.7-builds.txt
                    grep '4\\.8\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.8-builds.txt
                    grep '4\\.9\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.9-builds.txt
                    grep '4\\.10\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.10-builds.txt
                    grep '4\\.11\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.11-builds.txt
                    grep '4\\.12\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.12-builds.txt
                    grep '4\\.13\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.13-builds.txt

                    #Latest Builds
                    cat all-4.6-builds.txt|head -n 1|awk '{print $1}' >latest-4.6-build.txt
                    cat all-4.7-builds.txt|head -n 1|awk '{print $1}' > latest-4.7-build.txt
                    cat all-4.8-builds.txt|head -n 1|awk '{print $1}'  > latest-4.8-build.txt
                    cat all-4.9-builds.txt|head -n 1|awk '{print $1}'  > latest-4.9-build.txt
                    cat all-4.10-builds.txt|head -n 1|awk '{print $1}' > latest-4.10-build.txt
                    cat all-4.11-builds.txt|head -n 1|awk '{print $1}' > latest-4.11-build.txt
                    cat all-4.12-builds.txt|head -n 1|awk '{print $1}' > latest-4.12-build.txt
                    cat all-4.13-builds.txt|head -n 1|awk '{print $1}' > latest-4.13-build.txt

                    #All stable Builds
                    cat all-4.6-builds.txt | grep -v 'nightly\\|-rc\\|-fc' > all-4.6-stable-builds.txt
                    cat all-4.7-builds.txt | grep -v 'nightly\\|-rc\\|-fc' > all-4.7-stable-builds.txt
                    cat all-4.8-builds.txt | grep -v 'nightly\\|-rc\\|-fc' > all-4.8-stable-builds.txt
                    cat all-4.9-builds.txt | grep -v 'nightly\\|-rc\\|-fc' > all-4.9-stable-builds.txt
                    cat all-4.10-builds.txt | grep -v 'nightly\\|-rc\\|-fc' > all-4.10-stable-builds.txt
                    cat all-4.11-builds.txt | grep -v 'nightly\\|-rc\\|-fc' > all-4.11-stable-builds.txt


                    #Latest stable build
                    cat all-4.6-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.6-stable-build.txt
                    cat all-4.7-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.7-stable-build.txt
                    cat all-4.8-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.8-stable-build.txt
                    cat all-4.9-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.9-stable-build.txt
                    cat all-4.10-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.10-stable-build.txt
                    cat all-4.11-stable-builds.txt |head -n 1|awk '{print $1}' > latest-4.11-stable-build.txt
                    '''
                    }
                    catch (err)
                    {
                        echo 'Error ! Template preparation failed !'
                        env.FAILED_STAGE=env.STAGE_NAME
                        throw err
                    }
                }
            }
        }
    }
    post {
        always {
            archiveAllArtifacts("builds.raw.txt", "all-builds.txt", "all-4.6-builds.txt", "all-4.7-builds.txt",
                                  "all-4.8-builds.txt","all-4.9-builds.txt","all-4.10-builds.txt","all-4.11-builds.txt",
                                  "all-4.12-builds.txt", "all-4.13-builds.txt", "latest-4.6-build.txt","latest-4.7-build.txt","latest-4.8-build.txt",
                                  "latest-4.9-build.txt","latest-4.10-build.txt","latest-4.11-build.txt","latest-4.12-build.txt", "latest-4.13-build.txt",
                                  "all-4.6-stable-builds.txt","all-4.7-stable-builds.txt","all-4.8-stable-builds.txt",
                                  "all-4.9-stable-builds.txt","all-4.10-stable-builds.txt","all-4.11-stable-builds.txt",
                                   "latest-4.6-stable-build.txt", "latest-4.7-stable-build.txt","latest-4.8-stable-build.txt",
                                   "latest-4.9-stable-build.txt", "latest-4.10-stable-build.txt", "latest-4.11-stable-build.txt")
            cleanWs()
        }
    }
}
